const QUOTES = [
  "Like most misery, it started with apparent happiness - The Book Thief",
  "Competence is attractive - The Book Thief",
  "Pick your battles",
  "Tomorrow never comes because it's always today.",
  "Most of the time, people aren't doing things TO you. They're doing things FOR them.",
  "Gurbat mein creativity nahi hoti. First, get rich then become a philosopher - Shah Rukh Khan",
  "Only let people borrow what you can afford to lose.",
  "Your family doesn't always have your best interests at heart. That's why you go out and make new ones that you call friends.",
  "We may not get to choose how we die, but we can choose how we live. The universe may forget us, but it doesn't matter. Because we are the ants, and we'll keep marching on. - We are the ants",
  "There is nothng so bad that it couldn't be worse",
  "That's the thing about books ..they let u travel  without moving ur feet",
  "I'm wondering what to read next",
  "Take what you can ,give nothing back ",
  "Why is the rum... always gone?",
  "The only rule that matters is what u can and what u cannot",
  "Being still n doing nthng are two different things",
  "Our fate lives within us ...u only have to be brave enough to see it",
  "The king who roams fearlessly ",
  "It is in  hearing the voice of evil that we  can better appreciate the voice of god",
  "Hope is a mistake if you can't fix what is broken u will go insane",
  "The freedom to make my own mistakes was all I ever wanted",
  "Strong man is strongest alive",
  "The less you talk the more people think about your words",
  "Lord, don't move the mountain.. But give me the strength to climb it",
  "I gotta do what I gotta do.. U gotta do what u gotta do",
  "Life is always a matter of waiting for the right moment to act",
  "Be soo good that people can't ignore you",
  "Not everybody needs to know your story",
  "Oh, shoulda woulda coulda",
  "Prayer is when we talk to God, mediation is when we listen to god",
  "I would if I could, I can't so I shan't",
  "It's okay not to be okay",
  "Doing what the hell you want to do is always an option",
  "Don't ever let anyone tell you what u can do and what you cannot do",
  "You don't open a book.. you open a mind",
  "With all due respect to everybody.. Screw everybody",
  "Don't be someone's sometimes",
  "Life is what happens when you are busy making other plans",
  "Well keep calm and carry on",
  "Much said little understand/remembered and nothing done",
  "Every thing that kills me makes me feel alive",
  "Because it's just me, because no-one else makes sense",
  "It's not good its not bad.. Its just what it is ",
  "Be silly. Be kind. Be weird",
  "You are ur problem and you are ur solution",
  "We are all stories in the end",
  "Every mile will be worth the while",
  "Life hurts eddie, it just does",
  "Judge me by the people i avoid",
  "War and peace wrapped in the same soul",
  "Sometimes there is beauty in mundane",
  "Carpe diem, carpe noctem, and carpe vitam -seize the day, seize the night, and seize life",
  "This too shall pass",
  "One day at a time",
  "Someone get him a shot, he's thinking again",
  "U can't move backwards..u can only go forward.. umm false. U can go wherever u want. I guess the question is where do you want to go",
  "O captain, my captain!!!",
  "May be our favorite quotaes say more about us than about the stories and people we are quoting ",
  "You're both the fire and the water that extinguishes it. You're the narrator, the protagonist, and the sidekick. You're the storyteller and the story told. You are somebody's something but you are also you.",
  "I am not afraid of storms, for I am learning how to sail my ship.”",
  "Don't fight the fabric, change it",
  "Hold strong, brother",
  "Beautiful things don't ask for attention",
  "Conviction, it turns out, is a luxury of those on sidelines",
  "Do what you love and fuck the rest. I think we can live with that",
  "I know I'm in a city full of people with big, fat, neon-sign aspirations and I know it's not cool to say and it is not big and flashy ... but I love books and I want my life to be about what I actually love.",
  "Sometimes the best way to deal with disappointment in one arena is to accomplish something else",
  "How much money you earn is not the most important thing in the world. Whom you spend it with is",
];
